name: Build LaTeX documents

on:
  push:
    paths:
      - '**.tex'
      - '**.sty'
      - '**.cls'
      - '**/compile.yml'
  workflow_dispatch:

jobs:
  build-latex:
    runs-on: ubuntu-latest
    name: Compile LaTeX to PDF
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install texlive
        run: sudo apt-get update && sudo apt-get install -y texlive texlive-binaries texlive-fonts-recommended texlive-lang-european texlive-latex-base texlive-latex-extra
      - name: Compile LaTeX
        run: ./compile.sh
      - name: Archive pdf:s
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: |
            ./*/*.pdf
      - name: Archive texlive logs
        uses: actions/upload-artifact@v2
        with:
          name: texlive-logs
          path: |
            ./*/*.log

  # We build a bunch of low-res png:s in order to compare them to the original ones.
  generate-pngs:
    runs-on: ubuntu-latest
    needs: build-latex
    name: Generate PNGs from PDFs
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install poppler-utils
        run: sudo apt-get install -y poppler-utils
      - name: Fetch generated pdf:s
        uses: actions/download-artifact@v2
        with:
          name: pdfs
      - name: Generate png:s from pdf:s
        run: ./.github/scripts/img.sh
      - name: Archive png:s
        uses: actions/upload-artifact@v2
        with:
          name: pngs
          path: |
            **/*.pdf-*.png

  compare-pngs-tex:
    runs-on: ubuntu-latest
    needs: generate-pngs 
    name: Compare PNGs to PNGs from original TeX-files
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Fetch generated png:s
        uses: actions/download-artifact@v2
        with:
          name: pngs
      - name: Compare png:s to original png:s
        run: ./.github/scripts/img_cmp_tex.sh
      - name: Archive diff png:s
        uses: actions/upload-artifact@v2
        with:
          name: diff-pngs-tex
          path: |
            **/*.diff.png

  compare-pngs-pdf:
    runs-on: ubuntu-latest
    needs: generate-pngs
    name: Compare PNGs to PNGs from original PDF-files
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Fetch generated png:s
        uses: actions/download-artifact@v2
        with:
          name: pngs
      - name: Compare png:s to original png:s
        run: ./.github/scripts/img_cmp_pdf.sh
        env:
          USE_ORIGINAL_PDFS: true
      - name: Archive diff png:s
        uses: actions/upload-artifact@v2
        with:
          name: diff-pngs-pdf
          path: |
            **/*.diff.png